FROM tensorflow/tensorflow:1.14.0-gpu-py3

CMD ["bash"]

RUN apt-get update
RUN pip install --upgrade pip
RUN apt install -y libsm6 libxext6 libxrender-dev

WORKDIR /workspace
COPY requirements-gpu.txt .
RUN pip install flask uwsgi -r requirements-gpu.txt
COPY --from=wodndl895/ugatit-gpu /workspace/checkpoint /workspace/checkpoint

COPY . .

EXPOSE 3010
CMD uwsgi --http :3010 --wsgi-file app.py --callable app --master --processes 4 --threads 1 --wsgi-disable-file-wrapper
